//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApplication.UserServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference2.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUsers", ReplyAction="*")]
        ClientWebApplication.UserServiceReference2.LoginUsersResponse LoginUsers(ClientWebApplication.UserServiceReference2.LoginUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApplication.UserServiceReference2.LoginUsersResponse> LoginUsersAsync(ClientWebApplication.UserServiceReference2.LoginUsersRequest request);
        
        // CODEGEN: Generating message contract since element name userid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUsers", ReplyAction="*")]
        ClientWebApplication.UserServiceReference2.RegisterUsersResponse RegisterUsers(ClientWebApplication.UserServiceReference2.RegisterUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApplication.UserServiceReference2.RegisterUsersResponse> RegisterUsersAsync(ClientWebApplication.UserServiceReference2.RegisterUsersRequest request);
        
        // CODEGEN: Generating message contract since element name autoUserIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoUserId", ReplyAction="*")]
        ClientWebApplication.UserServiceReference2.autoUserIdResponse autoUserId(ClientWebApplication.UserServiceReference2.autoUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApplication.UserServiceReference2.autoUserIdResponse> autoUserIdAsync(ClientWebApplication.UserServiceReference2.autoUserIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUsers", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.UserServiceReference2.LoginUsersRequestBody Body;
        
        public LoginUsersRequest() {
        }
        
        public LoginUsersRequest(ClientWebApplication.UserServiceReference2.LoginUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public LoginUsersRequestBody() {
        }
        
        public LoginUsersRequestBody(string userId, string username, string password) {
            this.userId = userId;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.UserServiceReference2.LoginUsersResponseBody Body;
        
        public LoginUsersResponse() {
        }
        
        public LoginUsersResponse(ClientWebApplication.UserServiceReference2.LoginUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginUsersResult;
        
        public LoginUsersResponseBody() {
        }
        
        public LoginUsersResponseBody(bool LoginUsersResult) {
            this.LoginUsersResult = LoginUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUsers", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.UserServiceReference2.RegisterUsersRequestBody Body;
        
        public RegisterUsersRequest() {
        }
        
        public RegisterUsersRequest(ClientWebApplication.UserServiceReference2.RegisterUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string usertype;
        
        public RegisterUsersRequestBody() {
        }
        
        public RegisterUsersRequestBody(string userid, string username, string password, string usertype) {
            this.userid = userid;
            this.username = username;
            this.password = password;
            this.usertype = usertype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.UserServiceReference2.RegisterUsersResponseBody Body;
        
        public RegisterUsersResponse() {
        }
        
        public RegisterUsersResponse(ClientWebApplication.UserServiceReference2.RegisterUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterUsersResult;
        
        public RegisterUsersResponseBody() {
        }
        
        public RegisterUsersResponseBody(string RegisterUsersResult) {
            this.RegisterUsersResult = RegisterUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoUserId", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.UserServiceReference2.autoUserIdRequestBody Body;
        
        public autoUserIdRequest() {
        }
        
        public autoUserIdRequest(ClientWebApplication.UserServiceReference2.autoUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class autoUserIdRequestBody {
        
        public autoUserIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWebApplication.UserServiceReference2.autoUserIdResponseBody Body;
        
        public autoUserIdResponse() {
        }
        
        public autoUserIdResponse(ClientWebApplication.UserServiceReference2.autoUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autoUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string autoUserIdResult;
        
        public autoUserIdResponseBody() {
        }
        
        public autoUserIdResponseBody(string autoUserIdResult) {
            this.autoUserIdResult = autoUserIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientWebApplication.UserServiceReference2.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientWebApplication.UserServiceReference2.WebService1Soap>, ClientWebApplication.UserServiceReference2.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.UserServiceReference2.LoginUsersResponse ClientWebApplication.UserServiceReference2.WebService1Soap.LoginUsers(ClientWebApplication.UserServiceReference2.LoginUsersRequest request) {
            return base.Channel.LoginUsers(request);
        }
        
        public bool LoginUsers(string userId, string username, string password) {
            ClientWebApplication.UserServiceReference2.LoginUsersRequest inValue = new ClientWebApplication.UserServiceReference2.LoginUsersRequest();
            inValue.Body = new ClientWebApplication.UserServiceReference2.LoginUsersRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.username = username;
            inValue.Body.password = password;
            ClientWebApplication.UserServiceReference2.LoginUsersResponse retVal = ((ClientWebApplication.UserServiceReference2.WebService1Soap)(this)).LoginUsers(inValue);
            return retVal.Body.LoginUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApplication.UserServiceReference2.LoginUsersResponse> ClientWebApplication.UserServiceReference2.WebService1Soap.LoginUsersAsync(ClientWebApplication.UserServiceReference2.LoginUsersRequest request) {
            return base.Channel.LoginUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.UserServiceReference2.LoginUsersResponse> LoginUsersAsync(string userId, string username, string password) {
            ClientWebApplication.UserServiceReference2.LoginUsersRequest inValue = new ClientWebApplication.UserServiceReference2.LoginUsersRequest();
            inValue.Body = new ClientWebApplication.UserServiceReference2.LoginUsersRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ClientWebApplication.UserServiceReference2.WebService1Soap)(this)).LoginUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.UserServiceReference2.RegisterUsersResponse ClientWebApplication.UserServiceReference2.WebService1Soap.RegisterUsers(ClientWebApplication.UserServiceReference2.RegisterUsersRequest request) {
            return base.Channel.RegisterUsers(request);
        }
        
        public string RegisterUsers(string userid, string username, string password, string usertype) {
            ClientWebApplication.UserServiceReference2.RegisterUsersRequest inValue = new ClientWebApplication.UserServiceReference2.RegisterUsersRequest();
            inValue.Body = new ClientWebApplication.UserServiceReference2.RegisterUsersRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.usertype = usertype;
            ClientWebApplication.UserServiceReference2.RegisterUsersResponse retVal = ((ClientWebApplication.UserServiceReference2.WebService1Soap)(this)).RegisterUsers(inValue);
            return retVal.Body.RegisterUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApplication.UserServiceReference2.RegisterUsersResponse> ClientWebApplication.UserServiceReference2.WebService1Soap.RegisterUsersAsync(ClientWebApplication.UserServiceReference2.RegisterUsersRequest request) {
            return base.Channel.RegisterUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.UserServiceReference2.RegisterUsersResponse> RegisterUsersAsync(string userid, string username, string password, string usertype) {
            ClientWebApplication.UserServiceReference2.RegisterUsersRequest inValue = new ClientWebApplication.UserServiceReference2.RegisterUsersRequest();
            inValue.Body = new ClientWebApplication.UserServiceReference2.RegisterUsersRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.usertype = usertype;
            return ((ClientWebApplication.UserServiceReference2.WebService1Soap)(this)).RegisterUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApplication.UserServiceReference2.autoUserIdResponse ClientWebApplication.UserServiceReference2.WebService1Soap.autoUserId(ClientWebApplication.UserServiceReference2.autoUserIdRequest request) {
            return base.Channel.autoUserId(request);
        }
        
        public string autoUserId() {
            ClientWebApplication.UserServiceReference2.autoUserIdRequest inValue = new ClientWebApplication.UserServiceReference2.autoUserIdRequest();
            inValue.Body = new ClientWebApplication.UserServiceReference2.autoUserIdRequestBody();
            ClientWebApplication.UserServiceReference2.autoUserIdResponse retVal = ((ClientWebApplication.UserServiceReference2.WebService1Soap)(this)).autoUserId(inValue);
            return retVal.Body.autoUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApplication.UserServiceReference2.autoUserIdResponse> ClientWebApplication.UserServiceReference2.WebService1Soap.autoUserIdAsync(ClientWebApplication.UserServiceReference2.autoUserIdRequest request) {
            return base.Channel.autoUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApplication.UserServiceReference2.autoUserIdResponse> autoUserIdAsync() {
            ClientWebApplication.UserServiceReference2.autoUserIdRequest inValue = new ClientWebApplication.UserServiceReference2.autoUserIdRequest();
            inValue.Body = new ClientWebApplication.UserServiceReference2.autoUserIdRequestBody();
            return ((ClientWebApplication.UserServiceReference2.WebService1Soap)(this)).autoUserIdAsync(inValue);
        }
    }
}
