//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminWebPannel.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUsers", ReplyAction="*")]
        AdminWebPannel.UserServiceReference.LoginUsersResponse LoginUsers(AdminWebPannel.UserServiceReference.LoginUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<AdminWebPannel.UserServiceReference.LoginUsersResponse> LoginUsersAsync(AdminWebPannel.UserServiceReference.LoginUsersRequest request);
        
        // CODEGEN: Generating message contract since element name userid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUsers", ReplyAction="*")]
        AdminWebPannel.UserServiceReference.RegisterUsersResponse RegisterUsers(AdminWebPannel.UserServiceReference.RegisterUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<AdminWebPannel.UserServiceReference.RegisterUsersResponse> RegisterUsersAsync(AdminWebPannel.UserServiceReference.RegisterUsersRequest request);
        
        // CODEGEN: Generating message contract since element name autoUserIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoUserId", ReplyAction="*")]
        AdminWebPannel.UserServiceReference.autoUserIdResponse autoUserId(AdminWebPannel.UserServiceReference.autoUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<AdminWebPannel.UserServiceReference.autoUserIdResponse> autoUserIdAsync(AdminWebPannel.UserServiceReference.autoUserIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUsers", Namespace="http://tempuri.org/", Order=0)]
        public AdminWebPannel.UserServiceReference.LoginUsersRequestBody Body;
        
        public LoginUsersRequest() {
        }
        
        public LoginUsersRequest(AdminWebPannel.UserServiceReference.LoginUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public LoginUsersRequestBody() {
        }
        
        public LoginUsersRequestBody(string userId, string username, string password) {
            this.userId = userId;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdminWebPannel.UserServiceReference.LoginUsersResponseBody Body;
        
        public LoginUsersResponse() {
        }
        
        public LoginUsersResponse(AdminWebPannel.UserServiceReference.LoginUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginUsersResult;
        
        public LoginUsersResponseBody() {
        }
        
        public LoginUsersResponseBody(bool LoginUsersResult) {
            this.LoginUsersResult = LoginUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUsers", Namespace="http://tempuri.org/", Order=0)]
        public AdminWebPannel.UserServiceReference.RegisterUsersRequestBody Body;
        
        public RegisterUsersRequest() {
        }
        
        public RegisterUsersRequest(AdminWebPannel.UserServiceReference.RegisterUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string usertype;
        
        public RegisterUsersRequestBody() {
        }
        
        public RegisterUsersRequestBody(string userid, string username, string password, string usertype) {
            this.userid = userid;
            this.username = username;
            this.password = password;
            this.usertype = usertype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdminWebPannel.UserServiceReference.RegisterUsersResponseBody Body;
        
        public RegisterUsersResponse() {
        }
        
        public RegisterUsersResponse(AdminWebPannel.UserServiceReference.RegisterUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterUsersResult;
        
        public RegisterUsersResponseBody() {
        }
        
        public RegisterUsersResponseBody(string RegisterUsersResult) {
            this.RegisterUsersResult = RegisterUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoUserId", Namespace="http://tempuri.org/", Order=0)]
        public AdminWebPannel.UserServiceReference.autoUserIdRequestBody Body;
        
        public autoUserIdRequest() {
        }
        
        public autoUserIdRequest(AdminWebPannel.UserServiceReference.autoUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class autoUserIdRequestBody {
        
        public autoUserIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AdminWebPannel.UserServiceReference.autoUserIdResponseBody Body;
        
        public autoUserIdResponse() {
        }
        
        public autoUserIdResponse(AdminWebPannel.UserServiceReference.autoUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autoUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string autoUserIdResult;
        
        public autoUserIdResponseBody() {
        }
        
        public autoUserIdResponseBody(string autoUserIdResult) {
            this.autoUserIdResult = autoUserIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : AdminWebPannel.UserServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<AdminWebPannel.UserServiceReference.WebService1Soap>, AdminWebPannel.UserServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminWebPannel.UserServiceReference.LoginUsersResponse AdminWebPannel.UserServiceReference.WebService1Soap.LoginUsers(AdminWebPannel.UserServiceReference.LoginUsersRequest request) {
            return base.Channel.LoginUsers(request);
        }
        
        public bool LoginUsers(string userId, string username, string password) {
            AdminWebPannel.UserServiceReference.LoginUsersRequest inValue = new AdminWebPannel.UserServiceReference.LoginUsersRequest();
            inValue.Body = new AdminWebPannel.UserServiceReference.LoginUsersRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.username = username;
            inValue.Body.password = password;
            AdminWebPannel.UserServiceReference.LoginUsersResponse retVal = ((AdminWebPannel.UserServiceReference.WebService1Soap)(this)).LoginUsers(inValue);
            return retVal.Body.LoginUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdminWebPannel.UserServiceReference.LoginUsersResponse> AdminWebPannel.UserServiceReference.WebService1Soap.LoginUsersAsync(AdminWebPannel.UserServiceReference.LoginUsersRequest request) {
            return base.Channel.LoginUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdminWebPannel.UserServiceReference.LoginUsersResponse> LoginUsersAsync(string userId, string username, string password) {
            AdminWebPannel.UserServiceReference.LoginUsersRequest inValue = new AdminWebPannel.UserServiceReference.LoginUsersRequest();
            inValue.Body = new AdminWebPannel.UserServiceReference.LoginUsersRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((AdminWebPannel.UserServiceReference.WebService1Soap)(this)).LoginUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminWebPannel.UserServiceReference.RegisterUsersResponse AdminWebPannel.UserServiceReference.WebService1Soap.RegisterUsers(AdminWebPannel.UserServiceReference.RegisterUsersRequest request) {
            return base.Channel.RegisterUsers(request);
        }
        
        public string RegisterUsers(string userid, string username, string password, string usertype) {
            AdminWebPannel.UserServiceReference.RegisterUsersRequest inValue = new AdminWebPannel.UserServiceReference.RegisterUsersRequest();
            inValue.Body = new AdminWebPannel.UserServiceReference.RegisterUsersRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.usertype = usertype;
            AdminWebPannel.UserServiceReference.RegisterUsersResponse retVal = ((AdminWebPannel.UserServiceReference.WebService1Soap)(this)).RegisterUsers(inValue);
            return retVal.Body.RegisterUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdminWebPannel.UserServiceReference.RegisterUsersResponse> AdminWebPannel.UserServiceReference.WebService1Soap.RegisterUsersAsync(AdminWebPannel.UserServiceReference.RegisterUsersRequest request) {
            return base.Channel.RegisterUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdminWebPannel.UserServiceReference.RegisterUsersResponse> RegisterUsersAsync(string userid, string username, string password, string usertype) {
            AdminWebPannel.UserServiceReference.RegisterUsersRequest inValue = new AdminWebPannel.UserServiceReference.RegisterUsersRequest();
            inValue.Body = new AdminWebPannel.UserServiceReference.RegisterUsersRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.usertype = usertype;
            return ((AdminWebPannel.UserServiceReference.WebService1Soap)(this)).RegisterUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminWebPannel.UserServiceReference.autoUserIdResponse AdminWebPannel.UserServiceReference.WebService1Soap.autoUserId(AdminWebPannel.UserServiceReference.autoUserIdRequest request) {
            return base.Channel.autoUserId(request);
        }
        
        public string autoUserId() {
            AdminWebPannel.UserServiceReference.autoUserIdRequest inValue = new AdminWebPannel.UserServiceReference.autoUserIdRequest();
            inValue.Body = new AdminWebPannel.UserServiceReference.autoUserIdRequestBody();
            AdminWebPannel.UserServiceReference.autoUserIdResponse retVal = ((AdminWebPannel.UserServiceReference.WebService1Soap)(this)).autoUserId(inValue);
            return retVal.Body.autoUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AdminWebPannel.UserServiceReference.autoUserIdResponse> AdminWebPannel.UserServiceReference.WebService1Soap.autoUserIdAsync(AdminWebPannel.UserServiceReference.autoUserIdRequest request) {
            return base.Channel.autoUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<AdminWebPannel.UserServiceReference.autoUserIdResponse> autoUserIdAsync() {
            AdminWebPannel.UserServiceReference.autoUserIdRequest inValue = new AdminWebPannel.UserServiceReference.autoUserIdRequest();
            inValue.Body = new AdminWebPannel.UserServiceReference.autoUserIdRequestBody();
            return ((AdminWebPannel.UserServiceReference.WebService1Soap)(this)).autoUserIdAsync(inValue);
        }
    }
}
